version: "3.9"

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: duelyst
      POSTGRES_PASSWORD: duelyst
      POSTGRES_DB: duelyst
    ports:
      - 5431:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
