version: "3.9"

x-base-service: &base
  image: node:lts
  environment:
    REDIS_IP: redis
    POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
  depends_on:
    - db
    - redis
  entrypoint: bash
  working_dir: /app
  volumes:
    - .:/app
    - /app/node_modules

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: duelyst
      POSTGRES_PASSWORD: duelyst
      POSTGRES_DB: duelyst
    ports:
      - 5431:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    profiles:
      - donotstart
    restart: always
    ports:
      - 8080:8080

  api:
    <<: *base
    ports:
      - 3000:3000
    command: docker/start api

  game:
    <<: *base
    profiles:
      - donotstart
    ports:
      - 8000:8000
    command: docker/start game

  sp:
    <<: *base
    ports:
      - 8000:8000
    command: docker/start sp

  worker:
    <<: *base
    ports:
      - 3002:8080
    command: docker/start worker

  worker-ui:
    <<: *base
    profiles:
      - donotstart
    ports:
      - 3001:3000
    command: docker/start worker-ui

  migrate:
    image: node:lts
    profiles:
      - donotstart
    environment:
      DEBUG: "*"
      NODE_ENV: development
      POSTGRES_CONNECTION: "pg://duelyst:duelyst@db/duelyst"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: "bash -c"
    command: "yarn install --dev && yarn migrate:latest"
